version: '3.8'

services:
  consciousness-ai:
    build: .
    image: humor-consciousness:latest
    container_name: consciousness-core
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0,1
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      # GPU Memory allocation
      - CUDA_DEVICE_0_MEMORY=14GB  # RTX 4070 Ti Super (leave headroom)
      - CUDA_DEVICE_1_MEMORY=10GB  # GTX 1080 (leave headroom)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']  # Both GPUs
              capabilities: [gpu]
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./configs:/app/configs
    networks:
      - consciousness-net
    ports:
      - "8888:8888"  # Jupyter
      - "6006:6006"  # TensorBoard
      - "9090:9090"  # Prometheus
      - "5000:5000"  # API
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: consciousness-db
    environment:
      POSTGRES_USER: consciousness
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: consciousness_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - consciousness-net
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: consciousness-cache
    volumes:
      - redis-data:/data
    networks:
      - consciousness-net
    ports:
      - "6379:6379"

networks:
  consciousness-net:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 